# Generated by Django 5.1.1 on 2024-11-17 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseLogging', '0002_expense_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='user_id',
            new_name='user',
        ),
    ]
